### ISSUE TITLE
Use the `auto` keyword to our advantage

### ISSUE THREAD

**Issue by audreyseo** [cmu-mars/ros1-to-ros2-sandbox#45]
The fake template types like SubscriptionT or MessageT or CallbackT are messing with the code and generating errors whenever I try to build, so I should just replace that with the keyword `auto` since it's supposed to be C++ 11 or something compliant anyway.

I might look into more about the `auto` keyword because I really don't know anything about it, to be honest, but I also might just replace all of the types, especially in generated code.

Not sure if I'd be able to replace the types in the non-generated code because C++ can't even be represented by a context-free grammar, let alone a regular expression (I'm pretty sure that's the hierarchy of things? but it may not be), so we'll see what happens.

**Comment by ivoysey** [comment]
It seems that the `auto` keyword is how the C++ community is allowing themselves to accept that type inference is a fine thing that almost always works. If that is the right interpretation, I don't see much of a problem with using it often and vigorously in your output -- including taking source code that doesn't use `auto` and outputing source that does. If it works and `auto` can figure it out, and that's the modern style advice anyway, it seems harmless.

In ML-like languages the notion represented by `auto` is so internalized that there's no keyword for it because it's the default; all types are inferred unless you choose to add an annotation as documentation or to restrict a unification variable to clean up some error messages.
